# Dependencies
markdown:         kramdown
highlighter:      rouge

#gems: [jekyll-gist]

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink:        /:categories/:title/

# relative_permalinks: true

# Setup
title: "arodu Personal Website"
url:  https://arodu.github.io
baseurl: ""

description:      Software developer, Teacher and GNU/Linux fanboy.
author:
  name: "Alberto G. Rodriguez U."
  email: arodu.dev@gmail.com


excerpt_separator: "<!--more-->"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

paginate:         6

# Custom vars
version:          1.0.0

github:
  repo: https://github.com/arodu/www

logo: /public/avataaars.png

social:
  name: arodu
  links:
    - https://github.com/arodu
    - https://www.facebook.com/arodu.dev
    - https://www.linkedin.com/in/arodu
    - https://twitter.com/arodu
